### ISSUE TITLE
`requirements.txt` misnamed

### ISSUE THREAD

**Issue by stefanv** [mir-am/LightTwinSVM#4]
The file is currently called `requirments.txt`.

xref: https://github.com/openjournals/joss-reviews/issues/1252

**Comment by mir-am** [comment]
Thank you for creating this issue.
Actually, I was aware of it!

I am going to correct the name of the file now.

**Comment by mir-am** [comment]
The issue was fixed without breaking the installation scripts.
I may now close the issue.
